server:
  port: 8081

spring:
  application:
    name: fnb-platform

  # 1. Database
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 2. RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  
keycloak:
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

app:
  security:
    aes-secret: ${APP_AES_SECRET}

  payment:
    vnpay:
      api-url: ${VNPAY_API_URL}
      return-url: ${VNPAY_RETURN_URL}

# 4. MinIO (Custom)
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  external-url: ${MINIO_EXTERNAL_URL}
  buckets:
    public-assets: public-assets
    user-profiles: user-profiles
    tenant-assets: tenant-assets

logging:
  level:
    com.project.fnb: DEBUG
    org.springframework.security: INFO